export const DOUBT_REQUEST = "DOUBT_REQUEST";
export const DOUBT_FAILURE = "DOUBT_FAILURE";
export const DOUBT_GET_SUCCESS = "DOUBT_GET_SUCCESS";
export const DOUBT_ADD_SUCCESS = "DOUBT_ADD_SUCCESS";
