export const DETAILS_REQUEST = "DETAILS_REQUEST";
export const DETAILS_FAILURE = "DETAILS_FAILURE";
export const DETAILS_GET_SUCCESS = "DETAILS_GET_SUCCESS";
export const TUTOR_DETAILS_GET_SUCCESS = "TUTOR_DETAILS_GET_SUCCESS";
export const ALLTUTORS_GET_SUCCESS = "ALLTUTORS_GET_SUCCESS";
export const DETAILS_ADD_SUCCESS = "DETAILS_ADD_SUCCESS";
export const TUTOR_DETAILS_ADD_SUCCESS = "TUTOR_DETAILS_ADD_SUCCESS";
